# vim: set ft=ansible:
---
- name: Enable Zabbix repository
  tags: packer
  yum:
    name: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm

- name: Install the zabbix-agent package
  tags: packer
  yum:
    name: zabbix-agent
    state: present
