---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks started"
#
# - name: Set up ClientVM
#   hosts: bastions
#   gather_facts: false
#   become: true
#   tasks:
#   - name: Set up Client VM
#     include_role:
#       name: "ocp-client-vm"

    - debug:
        msg: "Software tasks completed"
