heat_template_version: 2018-03-02

description: New project and bastion for OpenShift

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: "nstephan-keypair"
      public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4LIAh+LeqBsODfR9YMqyk6E74hE9/FzyDsBf7pukER7alw99JLySZFeO7hL0COXrQlbweVDTwbU5GJrLSbUQZvgVOIbH/roAwMBjzuwdh7ibLyxZNdJs/6gLifWUXSmaj/JKXCr2Lg+527wRfePY+1mXJNMc+cbrezWoUpNlhw3D1NrcJnxldmRn6Rw0jnQdaz1PtAgMfX4Xftr9RV0GggtAwCGjViBK6WM+Fkfp4hT0EMVoCtwvhmEIzeaYaHofit3pW/KONp1DG/OisojUcDuQ6S7i5Mt35N1LmzR06ED4c8kOLMaqZ7UDupFOoILL/vqayVjL67trgcsTcJXI5
"
      user: "nate-redhat.com"

  network_private:
    type: OS::Neutron::Net
    properties:
      name: "nstephan-network"
      shared: false

  subnet_private:
    type: OS::Neutron::Subnet
    properties:
      name: "nstephan-subnet"
      network_id: { get_resource: network_private }
      cidr: 192.168.47.0/24
      dns_nameservers: [ 169.45.246.132 ]
      gateway_ip: 192.168.47.1
      allocation_pools:
      -  start: 192.168.47.10
         end: 192.168.47.99

  router:
    type: OS::Neutron::Router
    properties:
      name: "nstephan-router"
      external_gateway_info:
        network: "external"

  router_private_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet_private }

  bastion_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: "bastion_sg"
      description: "Bastion security group allows basic ICMP and SSH ingress and egress to *"
      rules:
        - protocol: ICMP
          direction: ingress
        - protocol: TCP
          direction: ingress
          port_range_min: 22
          port_range_max: 22
          remote_mode: remote_ip_prefix
          remote_ip_prefix: 0.0.0.0/0
        - protocol: TCP
          direction: egress
          remote_mode: remote_ip_prefix
          remote_ip_prefix: 0.0.0.0/0
  utility_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: "utility_sg"
      description: "Utility security group allows SSH from bastion and egress to *"
      rules:
        - protocol: TCP
          direction: ingress
          port_range_min: 22
          port_range_max: 22
          remote_mode: remote_group_id
          remote_group_id: bastion_sg

  bastion_port:
    type: OS::Neutron::Port
    properties:
      name: bastion-nstephan-port
      network: { get_resource: network_private }

  bastion_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "external"

  bastion_fip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: bastion_fip }
      port_id: { get_resource: bastion_port }
  
  clientvm:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        properties:
          name: clientvm
          image: rhel-guest-7.7
          key_name: { get_resource: keypair }
          flavor: m1.small
          security_groups:
            - {get_resource: bastion_sg }
            - {get_resource: utility_sg }
          networks:
            - network: { get_resource: network_private }
