- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step001
  - pre_infrastructure
  environment:
    OS_AUTH_URL: "{{ osp_auth_url }}"
    OS_USERNAME: "{{ osp_auth_username }}"
    OS_PASSWORD: "{{ osp_auth_password }}"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
    OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}"
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure - Dummy action"
    
    # - name: Set auth facts to access OpenStack
    #   set_fact:
    #     os_cloud_auth:
    #       auth_url: "{{ osp_auth_url }}"
    #       username: "{{ osp_auth_username }}"
    #       password: "{{ osp_auth_password }}"
    #       project_name: admin
    #       project_domain_name: Default
    #       user_domain_name: Default
    #       #auth_type: password
    #       region_name: RegionOne
    #       identity_api_version: 3

    # - name: Create location for clouds.yaml
    #   file:
    #     path: /etc/openstack
    #     state: directory
    
    # - name: Copy clouds.yaml to /etc/openstack
    #   template:
    #     source: ./files/clouds.yaml.j2
    #     dest: /etc/openstack/clouds.yaml

    - name: Create project for user
      os_project:
        # cloud: "{{ osp_auth_cloud }}"
        name: "{{ guid }}-project"
        state: present
        description: Project for user {{ opentlc_user }}
        enabled: True
        domain_id: "Default"
        endpoint_type: public
      register: _r_osp_project_name

    # - debug:
    #     var: _r_osp_project_name

    - name: set fact for newly created project
      set_fact:
        osp_project_creation: "{{ _r_osp_project_name }}"
    
    # - debug:
    #     var: osp_project_creation
    
    - name: Grant access to user on new project
      os_user_role:
        # cloud: "{{ osp_auth_cloud }}"
        state: present
        user: "{{ opentlc_user }}"
        role: "{{ item }}"
        project: "{{ _r_osp_project_name.project.name }}"
      with_items:
      - "_member_"
      - "swiftoperator"
    
    - name: Grant access to admin account on new project
      os_user_role:
        # cloud: "{{ osp_auth_cloud }}"
        state: present
        user: "{{ admin_user }}"
        role: "admin"
        project: "{{ _r_osp_project_name.project.name }}"
    
    - name: Set quotas on new project
      os_quota:
        # cloud: "{{ osp_auth_cloud }}"
        name: "{{ _r_osp_project_name.project.name }}"
        instances: "{{ quota_num_instances }}"
        cores: "{{ quota_num_cores }}"
        ram: "{{ quota_memory }}" #in MB
        volumes: "{{ quota_num_volumes }}"
        gigabytes: "{{ quota_volumes_gigs }}" #volume storage
        #loadbalancer: #when Octavia is available
        #pool: #when Octavia is available
        network: "{{ quota_networks }}"
        subnet: "{{ quota_subnets }}"
        router: "{{ quota_routers }}"
        floatingip: "{{ quota_fip }}"
        security_group: "{{ quota_sg }}"
        security_group_rule: "{{ quota_sg_rules }}"
    
    # - name: Create keypair for user
    #   os_keypair:
    #     cloud: "{{ osp_auth_cloud }}"
    #     name: "{{ opentlc_user }}-keypair"
    #     state: present
    #     public_key: "{{ user_pub_key }}"

      
