---
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes

- name: Promote to domain controller
  win_domain_controller:
    dns_domain_name: "{{ ec2_tag_internaldns }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
    domain_admin_user: "{{ ad_admin_user }}"
    domain_admin_password: "{{ ad_admin_password }}"
    state: domain_controller
  register: result
