- name: Create Heat stack from generated template
  environment:
    OS_AUTH_URL: "{{ osp_auth_url }}"
    OS_USERNAME: "{{ osp_auth_username }}"
    OS_PASSWORD: "{{ osp_auth_password }}"
    OS_PROJECT_NAME: "{{ osp_project_creation.project.name }}"
    OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
    OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}"
  os_stack:
    name: "{{ guid }}-base-stack"
    state: present
    template: "{{ heat_template }}"
  register: r_hot_out

- set_fact:
    hot_output: "{{ r_hot_out }}"

- debug:
    var: hot_output